# LIBUSB_INCLUDE_DIR
# LIBUSB_LIBRARIES
# LIBUSB_FOUND
include(LibFindMacros)

find_path(LIBUSB_INCLUDE_DIR
	libusb.h
	PATH_SUFFIXES libusb-1.0
)

find_library(LIBUSB_LIBRARY
	NAMES usb-1.0
)

set(LIBUSB_PROCESS_INCLUDES LIBUSB_INCLUDE_DIR)
set(LIBUSB_PROCESS_LIBS LIBUSB_LIBRARY)
libfind_process(LIBUSB)
